### ISSUE TITLE
Building produces broken typescript

### ISSUE THREAD

**Issue by mrshmllow** [pmndrs/three-stdlib#147]
![unknown-6.png](https://user-images.githubusercontent.com/40532058/163564605-3f3edc8f-e853-4ec3-8c37-980c83e31393.png)

Using almost anything this package causes crazy type/resolution errors. Building from master it produces type definitions that import random stuff that doesn't exist. For instance from one of those above errors, `src/nodes/utils/TimerNode.d.ts` imports from `"../inputs/FloatNode"` which doesn't exist at all. Using the latest from npm has the same issue

_sorry for how low quality this issue i am away from my computer right now_

**Comment by BenLune** [comment]
Hello,
I think I created this issue related to the same kind of problem : https://github.com/pmndrs/three-stdlib/issues/148
I hope it will be fixed soon...
Have a good day !

**Comment by mrshmllow** [comment]
same

**Comment by Methuselah96** [comment]
@drcmda @joshuaellis This seems quite problematic since it fails type-checking when `skipLibCheck` is set to `false`. I would like to help resolve this issue, but I'm not sure of the best path forward. It seems like the current solution of copying the types from `@types/three` will not be maintainable long-term as they keep diverging. What would you think of removing the attempt to copy types from `@types/three` and instead trying to enable `allowJs` and fixing any errors with that?

**Comment by Methuselah96** [comment]
Or if the goal is to keep them mostly aligned with the three examples, is there a way to know which examples have diverged and which ones haven't?

**Comment by Methuselah96** [comment]
@drcmda After looking into it some more, it appears that many of the examples have not been modified since they were copied from three. Here is a PR to resolve this issue while still sticking with the current strategy: https://github.com/pmndrs/three-stdlib/pull/176.
