### ISSUE TITLE
Reflector Code Different than Three.js

### ISSUE THREAD

**Issue by eduardfossas** [pmndrs/three-stdlib#317]
Hello!

I was studying the code of the Reflector.ts in the library and I realized that there is a modification in the tone mapping inside the onBeforeRender:

      let isSRGB = false
      if ('outputColorSpace' in renderer) isSRGB = renderer.outputColorSpace === 'srgb'
      else isSRGB = renderer.outputEncoding === 3001 // sRGBEncoding

      if ('outputColorSpace' in renderer) renderer.outputColorSpace = 'linear-srgb'
      else renderer.outputEncoding = 3000 // LinearEncoding
      renderer.toneMapping = NoToneMapping
[...]

      if ('outputColorSpace' in renderer) renderer.outputColorSpace = isSRGB ? 'srgb' : 'srgb-linear'
      else renderer.outputEncoding = isSRGB ? 3001 : 3000

I am very interested to know why this code was implemented. If someone could explain I would truly appreciate it.

**Comment by CodyJasonBennett** [comment]
This library supports older versions of three.js which used `encoding` constants such as `sRGBEncoding=3001` and `LinearEncoding=3000`. We have to support that and newer `colorSpace` workflows, so you'll notice old and new constants are hardcoded since #232. There are also polyfills for some core classes which have been removed or renamed.
