### ISSUE TITLE
Colors of TransformControls' Axes Not Rendering Correctly After Mouse Hover

### ISSUE THREAD

**Issue by TimJJTing** [pmndrs/three-stdlib#60]
- `three` version: 0.128.0
- `@react-three/fiber` version: 6.0.19
- `@react-three/drei` version: 4.3.3
- `node` version: 15.10.0
- `npm` version: 7.5.3

### Problem description:

Colors of TransformControls' axes become white after mouse hover.  
Their original color (red, green, and blue) are gone, which differs from the example shows in the [official Three.js documentation](https://threejs.org/examples/?q=Transf#misc_controls_transform).

Before mouse hover:  
<img width="311" alt="Screen Shot 2021-05-21 at 11 10 02 AM" src="https://user-images.githubusercontent.com/10464396/119076508-46d73f80-ba25-11eb-9897-0dd5e3ff7f66.png">

After mouse hover:  
<img width="416" alt="Screen Shot 2021-05-21 at 11 09 45 AM" src="https://user-images.githubusercontent.com/10464396/119076466-31faac00-ba25-11eb-90a1-9f3e1fcd71f4.png">

### Relevant code:
Not sure what causes this bug, but you can find it [here](https://drei.pmnd.rs/?path=/story/controls-transformcontrols--transform-controls-lock-st)

**Comment by flixr** [comment]
Running into the same problem...

**Comment by Amaranthos** [comment]
So I tried to track down the cause of this one was it's affecting a project where I'm trying to use TransformControls from [pmndrs/drei](https://github.com/pmndrs/drei). It seems like it was introduced in [cc079be](https://github.com/pmndrs/three-stdlib/commit/cc079be1d2bb5f619202341a2fa53a4cb006056c)

**Comment by orivier3** [comment]
I think I have found the root cause of this issue. I have looked at the [original implementation of the transform control in the threejs](https://threejs.org/examples/misc_controls_transform.html) library and tried to replicate the visual feedback. 

I netted out with something like this : 
![newHandles](https://user-images.githubusercontent.com/20699251/121559842-df525580-ca0e-11eb-95d0-7c9435831cc5.gif)

## Cause 
So what seems to be wrong in the [TransfromControl.js](https://github.com/pmndrs/three-stdlib/commit/cc079be1d2bb5f619202341a2fa53a4cb006056c) is the state management when the pointer is not hovering on a gizmo axis.  The error is probably in the following code block; here is my `TransformControl.js` from my node_modules folder. You can find the block [here at line 1273](https://github.com/pmndrs/three-stdlib/commit/cc079be1d2bb5f619202341a2fa53a4cb006056c#diff-b58ed75b1a1aff9ca07e396dd7f9a888843da850f959112cc830db2c3b3d590bL1273)
```javascript 
       // Hide disabled axes

        //@ts-ignore

        handle.material.opacity = handle.material.opacity || handle.material.opacity; //@ts-ignore

        handle.material.color = handle.material.color || handle.material.color.clone(); //@ts-ignore

        handle.material.color.copy(handle.material.color); //@ts-ignore

        handle.material.opacity = handle.material.opacity;

        if (!this.enabled) {
          //@ts-ignore
          handle.material.opacity *= 0.5; //@ts-ignore

          handle.material.color.lerp(new Color(1, 1, 1), 0.5);
        } else if (this.axis) {
          if (handle.name === this.axis) {
            //@ts-ignore
            handle.material.opacity = 1.0; //@ts-ignore

            handle.material.color.lerp(new Color(1, 1, 1), 0.5);
          } else if (this.axis.split('').some(function (a) {
            return handle.name === a;
          })) {
            //@ts-ignore
            handle.material.opacity = 1.0; //@ts-ignore

            handle.material.color.lerp(new Color(1, 1, 1), 0.5);
          } else {
            //@ts-ignore
            handle.material.opacity *= 0.25; //@ts-ignore

            handle.material.color.lerp(new Color(1, 1, 1), 0.5);
          }
        }
```
##  Broken code
This block of code doesn't make sense to me 
```javascript 
       // Hide disabled axes

        //@ts-ignore

        handle.material.opacity = handle.material.opacity || handle.material.opacity; //@ts-ignore

        handle.material.color = handle.material.color || handle.material.color.clone(); //@ts-ignore

        handle.material.color.copy(handle.material.color); //@ts-ignore

        handle.material.opacity = handle.material.opacity;
```
I suppose that it was used to cache the axis colour in a previous revision, but as @Amaranthos mentioned [cc079be](https://github.com/pmndrs/three-stdlib/commit/cc079be1d2bb5f619202341a2fa53a4cb006056c) commenting this block of code doesn't seem to do anything. 
Maybe @joshuaellis, this could be the key to solve that problem, but I couldn't make sense of it. 

##  Axes dissappearing
At the end of that code block 
``` javascript
  } else {
            //@ts-ignore
            handle.material.opacity *= 0.25; //@ts-ignore

            handle.material.color.lerp(new Color(1, 1, 1), 0.5);
          }
 ```
This called as soon as the component is enabled, for me resulting in the axes disappearing entirely before the first hover when dynamically attaching TransfromControl to an object, the `*=` is the culprit here. 

##  Managing the end of the hover state
Looking at the `pointerHover` event, the `axis` property is set to null when the user not hovering on top transform gizmo. So we can use that to reset the opacity of the gizmo. The following code created the gif that I shared at the top.

``` javascript
         if (!this.enabled) {  //component is not enabled. Hide the axes
          
           handle.material.opacity = 0; 

        } else if (this.axis) { 
          if (handle.name === this.axis) { // pointer hover an axis, set opacity of this.axis to 1 
            
            handle.material.opacity = 1.0;

          } else if (this.axis.split('').some(function (a) {  //don't understand this bit
            return handle.name === a;    
          })) {                                                

            handle.material.opacity = 1.0; 

          } else {  //set all other axis to 0.25 
            
            handle.material.opacity = 0.25; 
            
          }
        }else{   //when this.axis is null set all axis to maximum opacity expect the planar ones
          handle.material.opacity = handle.name==='XY'||handle.name==='YZ'||handle.name==='XZ'? 0.5 : 1;
        }
```


Please, @joshuaellis let me know the best course of action. Do you want me to create a PR with the following changes? 
I think it would be ideal for the @react/three-drei TransfromControl component to follow the original three js behaviour.

**Comment by joshuaellis** [comment]
@orivier3 we're using three-stdlib, so your fix would have to be applied there, but it's certainly more than welcome if you have an idea how to solve said issue!

**Comment by orivier3** [comment]
![newHandlesStoryboard](https://user-images.githubusercontent.com/20699251/121599944-af6d7700-ca3b-11eb-819f-c59e8c45f4c2.gif)

The solution was in the end pretty simple!  See the PR.
